### ISSUE TITLE
As a user, I want to see a map on the page so that I can eventually see stuff on the map on the page

### ISSUE THREAD

**Issue by mcfungster** [boolean-bobcats/civic-engagement#63]

**Comment by jmichelin** [comment]
Hey Rishi,

Is this story due today or tomorrow?

**Comment by rishishah-zzz** [comment]
@jmichelin Not sure to be honest

**Comment by jmichelin** [comment]
Do you think you will get it done today or tomorrow? I am fairly certain the size of 5 means it is due tomorrow :)

**Comment by rishishah-zzz** [comment]
Okay cool, I'll aim for that
